### ISSUE TITLE
performance improvement  suggestion

### ISSUE THREAD

**Issue by rodgomesc** [gev2002/react-native-vision-camera-v3-face-detection#1]
awesome work, btw didn't tested it yet, i have a suggestion that can improve it's performance for a few or even a lot of frames, the instantiation of the builder should happen only once instead of every frame, you can do that implementing it on the class constructor and reinstantiating it only if the props used on it changes

https://github.com/gev2002/react-native-vision-camera-v3-face-detection/blob/7af3a2d1033e73046a6c4315734bfa5804cff398/android/src/main/java/com/visioncamerav3facedetection/VisionCameraV3FaceDetectionModule.kt#L28-L35

**Comment by gev2002** [comment]
> awesome work, btw didn't tested it yet, i have a suggestion that can improve it's performance for a few or even a lot of frames, the instantiation of the builder should happen only once instead of every frame, you can do that implementing it on the class constructor and reinstantiating it only if the props used on it changes
> 
> https://github.com/gev2002/react-native-vision-camera-v3-face-detection/blob/7af3a2d1033e73046a6c4315734bfa5804cff398/android/src/main/java/com/visioncamerav3facedetection/VisionCameraV3FaceDetectionModule.kt#L28-L35

Thank you, I will do it soon.

**Comment by gev2002** [comment]
Hello, I did this with my new plugins, and I will do it on these plugins when I find some free time.
