### ISSUE TITLE
Question: Non Google Device

### ISSUE THREAD

**Issue by nolife08021** [gev2002/react-native-vision-camera-v3-face-detection#3]
Hi, is this plugin working for device that without google service? like Huawei Nova.
I done install it and test it, after log "Worklets loaded successfully", my device just display full black screen.

    "react": "18.2.0",
    "react-native": "0.71.17",
    "react-native-vision-camera": "^3.9.0",
    "react-native-vision-camera-v3-face-detection": "^1.1.3",
    "react-native-worklets-core": "^0.4.0",

**Comment by gev2002** [comment]
Hello, this module should work because I integrated without using play-services.

**Comment by nolife08021** [comment]
hi, but i my side didnt display out the camera. just blank UI.

```
<Camera
          options={{
            performanceMode: "fast",
          }}
          style={StyleSheet.absoluteFill}
          // device={device}
          callback={(data) => {
            console.log("Face Data");
            console.log(data);
          }}
          // {...props}
        />
```

**Comment by nolife08021** [comment]
after i add "isActive"={true}, the camera shows out, but the camera just display in 1 sec then it just freeze on it

**Comment by nolife08021** [comment]
working after add photo={true}
